name: Mehdi Sakout
description: "Androidist, Designer and BeatMaker"
meta_description: "Androidist, Designer and BeatMaker"

baseurl: &baseurl /
aboutPage: true
contactPage: true
portfolioPage: true

apps :
    -   
        title: 'Elbotola'
        description: 'Ranked as #1 Sport App In Morocco, the app serves more than 100k active users and provides soccer news, live scores, fixtures, results ... well everything about sport'
        logo: 'https://lh5.ggpht.com/xmZI9GFAJIzxhUu9IaSlRf0SjkYvquFFy7vYQ4e8SkarWzhKUb2RyBQMHPOQIt28JSs2=w300-rw'
    -   
        title: 'Elbotola chat'
        description: 'Group chat application dedicated for Sports Fans, providing different public rooms for famous teams and hot matches. The app is a SPA (single page application) and comes with a smooth browsing experience and a fancy UI that fits perfectly with app theme.'
        logo: 'https://lh3.googleusercontent.com/a_yR8XVeOem614ZSRYTYUOARM2pKWXVzshz3NTqtF8KUr3DePQ1GG9xo_B_-HbgEAQ=w300-rw'
    -
        title: 'Maintool'
        description: "Awesome Iot Project that's aimed to transform any watch to a smartWatch, the app offers many special features like : Heart rate, Steps Walked, Skin and ambient temperature ..."
        logo: /assets/images/apps/maintool.png
    -   
        title: 'Instatube'
        description: "Youtube Music alternative, it allows listening to youtube music/videos in Background even if the screen is Off. it's Distributed privately due to Google terms and conditions, PM me if you need a preview"
        logo: /assets/images/apps/instatube.png
    -   
        title: 'MarocAnnonces'
        description: 'Second classifieds App in Morocco after Avito'
        logo: https://lh3.ggpht.com/-mxelHLzXCiIXVTKgSdmLw0sjFj95AgOlyZrObg0l7xB2Ppf8TnVlpaq-Y-Wcu5RuwXH=w300-rw

markdown: kramdown
highlighter: rouge

gems :
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

paginate: 20

domain_name: 'http://medyo.github.io'
google_analytics: 'UA-70829892-1'
disqus: true
disqus_shortname: 'medyo80'

# Details for the RSS feed generator
url:            'http://medyo.github.io/'
author:         'Mehdi Sakout'
authorTwitter:  'medyo80'
authorTwitterUrl:  'https://twitter.com/MedyO80'
authorLinkedinUrl: 'http://ma.linkedin.com/in/elmehdisakout'
authorFacebookUrl: 'https://www.facebook.com/the.medy'
authorGPlusUrl: 'https://plus.google.com/+ElMehdiSakout'
permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
